name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BUILD: "cp37-macosx_x86_64 cp37-manylinux_x86_64 cp37-win_amd64"
          CIBW_BEFORE_BUILD: "pip install scikit-build"
          CIBW_BEFORE_ALL_LINUX: "yum install -y swig cmake && python -m pip install scikit-build"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5 scikit-build

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
